### ISSUE TITLE
Can't install gem

### ISSUE THREAD

**Issue by cannikin** [sproutit/sproutcore-abbot#1]
Trying to install the sproutit-sproutcore gem on Mac OSX and getting the following error:

<pre>tesla:~ rob$ sudo gem18 install sproutit-sproutcore
ERROR:  While executing gem ... (NoMethodError)
  undefined method 'each' for nil:NilClass</pre>

Afterwords, trying to perform any gem command (even `gem -h`!) errors out:

<pre>tesla:~ rob$ gem list
/Library/Ruby/Site/1.8/rubygems/gem_path_searcher.rb:98:in `lib_dirs_for': undefined method `join' for nil:NilClass (NoMethodError)
  from /Library/Ruby/Site/1.8/rubygems/gem_path_searcher.rb:24:in `initialize'
  from /Library/Ruby/Site/1.8/rubygems/gem_path_searcher.rb:23:in `each'
  from /Library/Ruby/Site/1.8/rubygems/gem_path_searcher.rb:23:in `initialize'
  from /Library/Ruby/Site/1.8/rubygems.rb:888:in `new'
  from /Library/Ruby/Site/1.8/rubygems.rb:888:in `searcher'
  from /Library/Ruby/Site/1.8/rubygems.rb:887:in `synchronize'
  from /Library/Ruby/Site/1.8/rubygems.rb:887:in `searcher'
  from /Library/Ruby/Site/1.8/rubygems.rb:527:in `find_files'
  from /Library/Ruby/Site/1.8/rubygems.rb:1131
  from /usr/bin/sc-init:9:in `require'
  from /usr/bin/sc-init:9</pre>

Running any of the sc- commands gives the same error.  I need to manually delete all the sproutcore gem files (cache, gems, specifications) in order to get `gem` to work again.

I'm running rubygems 1.3.4 and Ruby 1.8.6. 

I've also tried the instructions from the detailed Prerequisites section from http://wiki.sproutcore.com/Abbot-Setting+Up and still no luck.

**Comment by mattmccray** [comment]
Same here. I'm running on Mac 10.5.7, RubyGems 1.3.1, and Ruby 1.8.6.

**Comment by rpitting** [comment]
Fixing this issue is described at http://wiki.sproutcore.com/Abbot-GemFixup

**Comment by wagenet** [comment]
This is now far out of date.
