### ISSUE TITLE
sc-gen Not Listing Any Generators

### ISSUE THREAD

**Issue by ColinCampbell** [sproutit/sproutcore-abbot#11]
Running sc-gen doesn't list any generators, and, for example,

```
sc-gen model MyApp.Record
```

doesn't work at all.

**Comment by zimbatm** [comment]
Hi ColinCampbell,

I'm not a core dev, but I found a workaround. Try symlinking the gen folder in the lib directory. I think they forgot to fix that path when they moved things into the lib/ dir.

```
cd /path/to/abbot/lib;
ln -s ../gen gen
```

**Comment by wagenet** [comment]
Thanks! It's now fixed.
