### ISSUE TITLE
Proxy POST broken?

### ISSUE THREAD

**Issue by charlesjolley** [sproutit/sproutcore-abbot#20]
From mailing list:

Hi,

I've updated Abbot this morning to 1.4. I've followed the instructions
here : http://github.com/sproutit/sproutcore-abbot/wiki/Using-Abbot-1.4-From-Source

I'm using the proxy to communicate with my REST server. Everything
works fine when I'm using GET requests, but POST requests doesn't seem
to work ; all I get is "!! Unexpected error while processing request:
execution expired" logged in the console.

Where does this come from ? Abbot ? Ruby ?

Some versions : Abbot 1.4, SC from master branch, Ruby 1.8.7, Rails
3.0.0
## 

I don't immediately have a good way to test this.  Any ideas?

**Comment by wagenet** [comment]
This commit may fix it. http://github.com/sproutit/sproutcore-abbot/commit/a73b9bad1e308a52aa119a7722039cc6edc9e699
The person who first reported it said he'd test it on Monday.

**Comment by wagenet** [comment]
Apparently this is a two part issue. This fixes the other part: http://github.com/sproutit/sproutcore-abbot/commit/0b473f62acd5a678743de6333bdc9fed1366d0c8
