### ISSUE TITLE
sc-docs for abbot (by bundle-install) is broken

### ISSUE THREAD

**Issue by fcool** [sproutit/sproutcore-abbot#21]
I checked out abbot to
~/sprout/core/abbot

and used in my project directory the bundle-installation

sc-build and sc-server run very smooth now but sc-docs wont generate anything:

Error is:
Unable to access jarfile ~/sprout/core/abbot/lib/vendor/jsdoc/jsrun.jar

(for every target)

After symlinking ~/sprout/core/abbot/lib/sproutcore/vendor with ~/sprout/core/abbout/lib/vendor

this error disappeared but now sc-docs complains:
js: Couldn't open file "~/sprout/core/abbot/lib/sproutcore/publish.js".

**Comment by wagenet** [comment]
Sounds like an issue with the directory reorganization.

**Comment by wagenet** [comment]
Got a fix for this. Will upload shortly.

**Comment by wagenet** [comment]
http://github.com/sproutit/sproutcore-abbot/commit/97589716a20e7f82a331f919f64109e80c02732a
