### ISSUE TITLE
Make 1.4 Release Notes

### ISSUE THREAD

**Issue by wagenet** [sproutit/sproutcore-abbot#30]
We need release notes.

**Comment by ialexi** [comment]
A few things off the top of my head:
- Error Catcher! Yay!
- background task queue.
- CollectionView fast path. Still says "warning" in comments, but should be pretty stable now. Still needs more people to test it though.
- Lots of touch fixes
  - Touch intercept support: hasTouchIntercept, I think? But that API could potentially change, so may not want to mention it too much (naming is a bit off; "hasTouchIntercept" should be "wantsTouchIntercept" or something).
- wantsAcceleratedLayer

I thought we added an Automatic Bug Fixer, but couldn't find it.

**Comment by wagenet** [comment]
https://gist.github.com/4a73beb56f9191e3cac8
