### ISSUE TITLE
SelectFieldView null value causes error

### ISSUE THREAD

**Issue by lsiden** [sproutit/sproutcore-abbot#4]
http://github.com/sproutit/sproutcore/blob/master/frameworks/desktop/views/select_field.js#L183 states that a null value in the options list to a SelectFieldView should generate a place-holder in the rendered list and adjacent code implements this correctly.  However, this will cause an exception on line 262 (~ "no method objectAt for nil").

Please apply this patch to correct it: http://gist.github.com/393400

I am posting this here because sproutit/sproutcore does not have an Issues section.

**Comment by wagenet** [comment]
Already fixed
